<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    protected $table = 'reports';

    protected $primaryKey = 'id';

    public $incrementing = false;

    protected $keyType = 'string';

    protected $fillable = [
        'id', 'generated_by', 'report_type', 'content'
    ];

    protected $casts = [
        'created_at' => 'datetime',
    ];

    // Relationship with Account (Generated By)
    public function generatedBy()
    {
        return $this->belongsTo(Account::class, 'generated_by', 'user_id');
    }
}
