<!DOCTYPE html>
@include('includes.head')
    <body>
        
        <!--   NAV -->
        @include('includes.nav')
        <div class="columns" id="app-content">
        @include('cadmin.menu')
    

            <div class="column is-10" id="page-content">
                    <div class="content-header">
        <h4 class="title is-4">Generate Report</h4>        
    </div>

    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered">Report Generation</h1>
    
            <form>
                <div class="columns">
                    <!-- Report Information -->
                    <div class="column is-half">
                        <div class="card">
                            <div class="card-content">
                                <p class="title is-4">Report Information</p>
    
                                <div class="field">
                                    <label class="label">Generated By</label>
                                    <div class="control">
                                        <div class="select is-fullwidth">
                                            <select required>
                                                <option value="">Select Admin</option>
                                                <option>Admin 1</option>
                                                <option>Admin 2</option>
                                                <option>Admin 3</option>
                                                <!-- Dynamically populate this list with admins -->
                                            </select>
                                        </div>
                                    </div>
                                </div>
    
                                <div class="field">
                                    <label class="label">Report Type</label>
                                    <div class="control">
                                        <div class="select is-fullwidth">
                                            <select required>
                                                <option value="">Select Report Type</option>
                                                <option>Prisoner Statistics</option>
                                                <option>Request Status</option>
                                                <option>Training Programs Overview</option>
                                                <option>Job Assignments</option>
                                                <option>Other</option>
                                                <!-- Dynamically populate this list with report types -->
                                            </select>
                                        </div>
                                    </div>
                                </div>
    
                            </div>
                        </div>
                    </div>
    
                    <!-- Report Details -->
                    <div class="column is-half">
                        <div class="card">
                            <div class="card-content">
                                <p class="title is-4">Report Details</p>
    
                                <div class="field">
                                    <label class="label">Start Date</label>
                                    <div class="control">
                                        <input class="input" type="date" required>
                                    </div>
                                </div>
    
                                <div class="field">
                                    <label class="label">End Date</label>
                                    <div class="control">
                                        <input class="input" type="date" required>
                                    </div>
                                </div>
    
                                <div class="field">
                                    <label class="label">Additional Notes</label>
                                    <div class="control">
                                        <textarea class="textarea" placeholder="Enter any additional notes or context for the report"></textarea>
                                    </div>
                                </div>
    
                            </div>
                        </div>
                    </div>
    
                </div>
    
                <!-- Submit and Reset Button -->
                <div class="field is-grouped is-grouped-right">
                    <div class="control">
                        <button class="button is-link">Generate Report</button>
                    </div>
                    <div class="control">
                        <button class="button is-light" type="reset">Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
            </div>
        </div>

       @include('includes.footer_js')
    </body>

</html>
