<!DOCTYPE html>
@include('includes.head')

<body>
    @include('includes.nav')

    <div class="columns" id="app-content">
        @include('cadmin.menu')

        <div class="column is-10" id="page-content">
            <div class="content-header"></div>

            <section class="section">
                <div class="container">
                    <h1 class="title has-text-centered">Report Generation</h1>

                    <form action="{{ route('report.generate') }}" method="POST">
                        @csrf

                        <div class="columns">
                            <!-- Report Information -->
                            <div class="column is-half">
                                <div class="card">
                                    <div class="card-content">
                                        <p class="title is-4">Report Information</p>

                                        <div class="field">
                                            <label class="label">Generated By</label>
                                            <div class="control">
                                                <div class="select is-fullwidth">
                                                    <select name="generated_by" required>
                                                        <option value="">Select Admin</option>
                                                        @foreach($admins as $admin)
                                                            <option value="{{ $admin->id }}">{{ $admin->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="field">
                                            <label class="label">Report Type</label>
                                            <div class="control">
                                                <div class="select is-fullwidth">
                                                    <select name="report_type" id="report_type" required onchange="handleReportTypeChange()">
                                                        <option value="">Select Report Type</option>
                                                        <option value="all_accounts">All Accounts</option>
                                                        <option value="staff_in_prison">Staff in Chosen Prison</option>
                                                        <option value="prisoners_in_prison">Prisoners in Chosen Prison</option>
                                                        <option value="all_prisons">All Prisons and Their Details</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="field" id="prisonDropdown" style="display: none;">
                                            <label class="label">Choose a Prison</label>
                                            <div class="control">
                                                <div class="select is-fullwidth">
                                                    <select name="prison_id" id="prison_id">
                                                        <option value="">Select Prison</option>
                                                        @foreach($prisons as $prison)
                                                            <option value="{{ $prison->id }}">{{ $prison->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <!-- Report Details -->
                            <div class="column is-half">
                                <div class="card">
                                    <div class="card-content">
                                        <p class="title is-4">Report Details</p>

                                        <div class="field">
                                            <label class="label">Start Date</label>
                                            <div class="control">
                                                <input class="input" type="date" name="start_date" required>
                                            </div>
                                        </div>

                                        <div class="field">
                                            <label class="label">End Date</label>
                                            <div class="control">
                                                <input class="input" type="date" name="end_date" required>
                                            </div>
                                        </div>

                                        <div class="field">
                                            <label class="label">Additional Notes</label>
                                            <div class="control">
                                                <textarea class="textarea" name="notes" placeholder="Enter any additional notes or context for the report"></textarea>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Submit and Reset Button -->
                        <div class="field is-grouped is-grouped-right">
                            <div class="control">
                                <button class="button is-link" type="submit">Generate Report</button>
                            </div>
                            <div class="control">
                                <button class="button is-light" type="reset">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>

    @include('includes.footer_js')

    <script>
        function handleReportTypeChange() {
            const reportType = document.getElementById('report_type').value;
            const prisonDropdown = document.getElementById('prisonDropdown');

            if (reportType === 'staff_in_prison' || reportType === 'prisoners_in_prison') {
                prisonDropdown.style.display = 'block';
            } else {
                prisonDropdown.style.display = 'none';
            }
        }
    </script>
</body>
</html>
