<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PIMS - View Generated Reports</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: 'Poppins', sans-serif;
      background: linear-gradient(135deg, #e6e9f0 0%, #eef1f5 100%);
      min-height: 100vh;
      padding: 20px;
    }
    .pims-app-container {
      max-width: 1400px;
      margin: 0 auto;
    }
    .pims-content-area {
      background: #ffffff;
      border-radius: 12px;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
      padding: 30px;
      margin-bottom: 20px;
    }
    .pims-report-title {
      font-size: 28px;
      font-weight: 600;
      color: #1a237e;
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 25px;
    }
    .pims-report-table {
      width: 100%;
      border-collapse: separate;
      border-spacing: 0;
      background: #fff;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
    }
    .pims-report-table th, .pims-report-table td {
      padding: 12px 14px;
      text-align: left;
      border-bottom: 1px solid #e0e7ff;
      font-size: 13px;
    }
    .pims-report-table th {
      background: #e8eaf6;
      color: #1a237e;
      font-weight: 600;
      position: sticky;
      top: 0;
      z-index: 10;
    }
    .pims-report-table tbody tr:hover {
      background: #f8fafc;
    }
    .pims-btn {
      padding: 8px 16px;
      border: none;
      border-radius: 6px;
      cursor: pointer;
      font-size: 13px;
      font-weight: 500;
      display: inline-flex;
      align-items: center;
      gap: 6px;
      transition: background 0.3s;
    }
    .pims-btn-view {
      background: #3f51b5;
      color: #fff;
    }
    .pims-btn-view:hover {
      background: #303f9f;
    }
    .pims-modal {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.5);
      z-index: 1000;
      justify-content: center;
      align-items: center;
    }
    .pims-modal-content {
      background: #fff;
      border-radius: 12px;
      padding: 20px;
      max-width: 800px;
      width: 90%;
      max-height: 80vh;
      overflow-y: auto;
      position: relative;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
    }
    .pims-modal-close {
      position: absolute;
      top: 10px;
      right: 15px;
      font-size: 24px;
      cursor: pointer;
      color: #34495e;
    }
    .pims-modal-content h2 {
      font-size: 20px;
      font-weight: 600;
      color: #1a237e;
      margin-bottom: 15px;
    }
    .pims-modal-content p {
      font-size: 14px;
      color: #34495e;
      margin: 8px 0;
    }
    .pims-modal-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 15px;
    }
    .pims-modal-table th, .pims-modal-table td {
      border: 1px solid #e0e7ff;
      padding: 10px;
      font-size: 13px;
      text-align: left;
    }
    .pims-modal-table th {
      background: #e8eaf6;
      color: #1a237e;
      font-weight: 600;
    }
    .pims-error-message {
      color: #e74c3c;
      font-size: 14px;
      text-align: center;
      margin: 20px 0;
    }
    .pims-no-data {
      text-align: center;
      font-size: 16px;
      color: #34495e;
      padding: 20px;
    }
    @media (max-width: 768px) {
      .pims-report-table {
        display: block;
        overflow-x: auto;
      }
      .pims-modal-content {
        width: 95%;
        padding: 15px;
      }
    }
  </style>
</head>
<body>
@include('includes.nav');
  <div class="pims-app-container">
    @include('cadmin.menu');
    <div class="pims-content-area">
      <h1 class="pims-report-title">
        <i class="fas fa-file-alt"></i> View Generated Reports
      </h1>
      @if (session('error'))
        <div class="pims-error-message">{{ session('error') }}</div>
      @endif
      @if (empty($reports))
        <div class="pims-no-data">No reports found.</div>
      @else
        <table class="pims-report-table" id="pimsReportsTable">
          <thead>
            <tr>
              <th>ID</th>
              <th>Generated By</th>
              <th>Report Type</th>
              <th>Generated Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($reports as $report)
              <tr>
                <td>{{ $report['id'] }}</td>
                <td>{{ $report['generated_by'] }}</td>
                <td>{{ $report['report_type'] }}</td>
                <td>{{ $report['created_at'] }}</td>
                <td>
                  <button class="pims-btn pims-btn-view" onclick="viewReportDetails('{{ addslashes($report['content']) }}')">
                    <i class="fas fa-eye"></i> View Details
                  </button>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      @endif
    </div>
  </div>

  <div id="reportModal" class="pims-modal">
    <div class="pims-modal-content">
      <span class="pims-modal-close" onclick="closeModal()">×</span>
      <h2>Report Details</h2>
      <div id="reportDetails"></div>
    </div>
  </div>

  <script>
    function viewReportDetails(content) {
      try {
        // Parse JSON content
        const parsedContent = JSON.parse(content);
        const modal = document.getElementById('reportModal');
        const details = document.getElementById('reportDetails');
        let html = '';

        // Handle report content (from generate.blade.php)
        if (parsedContent.intro && parsedContent.table) {
          html += `
            <p><strong>Title:</strong> ${parsedContent.intro.title || 'N/A'}</p>
            <p><strong>Report Type:</strong> ${parsedContent.intro.report_type || 'N/A'}</p>
            <p><strong>Selected Prisons:</strong> ${parsedContent.intro.selected_prisons || 'N/A'}</p>
            <p><strong>Generated Date:</strong> ${parsedContent.intro.generated_date || 'N/A'}</p>
          `;
          if (Array.isArray(parsedContent.table)) {
            html += '<table class="pims-modal-table">';
            parsedContent.table.forEach((row, index) => {
              html += '<tr>';
              row.forEach(cell => {
                const tag = index === 0 ? 'th' : 'td';
                html += `<${tag}>${cell || 'N/A'}</${tag}>`;
              });
              html += '</tr>';
            });
            html += '</table>';
          } else {
            html += '<p>No table data available.</p>';
          }
        }
        // Handle navigation tracking (e.g., "Viewed reports list")
        else if (parsedContent.action) {
          html += `<p><strong>Action:</strong> ${parsedContent.action || 'N/A'}</p>`;
          html += `<p><strong>Timestamp:</strong> ${parsedContent.timestamp || 'N/A'}</p>`;
        }
        // Fallback for unexpected content
        else {
          html += '<p>Unknown report content format.</p>';
        }

        details.innerHTML = html;
        modal.style.display = 'flex';
      } catch (error) {
        console.error('Error parsing report content:', error.message);
        document.getElementById('reportDetails').innerHTML = '<p class="pims-error-message">Failed to load report details.</p>';
        document.getElementById('reportModal').style.display = 'flex';
      }
    }

    function closeModal() {
      document.getElementById('reportModal').style.display = 'none';
      document.getElementById('reportDetails').innerHTML = '';
    }

    // Close modal when clicking outside
    window.onclick = function(event) {
      const modal = document.getElementById('reportModal');
      if (event.target === modal) {
        closeModal();
      }
    };
  </script>
</body>
</html>